language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - mysql -e 'CREATE DATABASE petify;'

before_script:
  - chmod 777 -R storage
  - cp .env.travis .env
  - composer install --no-interaction
  - npm install

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

script:
  - php artisan key:generate
  - php artisan migrate --seed
  - vendor/bin/phpunit